### ISSUE TITLE
Liferea can't read rss feed

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#478]
this one https://itch.io/games/newest/platform-linux.xml

**Comment by stqn1** [comment]
It was me who reported the issue to fasterthanlime. I am using Liferea 1.10.8 (latest "stable" version on Gentoo).

Liferea doesn’t report any error, but the feed stays empty. I can see in Firefox that it contains many articles.

I’ll try to update to a more recent version to see if it helps.

**Comment by josefnpat** [comment]
There are quite a few errors with this feed: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fitch.io%2Fgames%2Fnewest%2Fplatform-linux.xml

**Comment by stqn1** [comment]
I have now tried with Liferea 1.10.16 (most recent version available on Gentoo), 1.10.18, 1.10.19 (latest upstream stable version), and 1.11.7 (latest unstable version) and they behave exactly the same.

**Comment by leafo** [comment]
it should be fixed now, there was a nesting issue with the markup

**Comment by stqn1** [comment]
Yes it’s now working with Liferea 1.10.8, thanks!
(The validator still isn’t happy though ;) )

**Comment by josefnpat** [comment]
as @stqn1 says - works, but doesn't validate.

**Comment by leafo** [comment]
it will never validate, we use non-standard tags for additional metadata.

**Comment by leafo** [comment]
That would be if we wanted to embed xml as text in another xml node. We want them to be first class nodes.
