### ISSUE TITLE
Double email notifications for new builds

### ISSUE THREAD

**Issue by quyse** [itchio/itch.io#689]
![2017-07-27-163942_467x389_scrot](https://user-images.githubusercontent.com/416215/28673094-4c3d69e4-72ea-11e7-96d9-ea1069ca9bd2.png)

**Comment by leafo** [comment]
Did this just start happening recently or has this always been like this?

**Comment by quyse** [comment]
Hi leafo, this project was abandoned by me for a while, and I just recently started again uploading new builds to it. I looked through my emails, and yes, all 4 emails I have (starting from July 16) have two duplicated lines (some about 3 builds like the one above, some about a single build).

Also seems like I don't receive email notifications about new builds in projects I'm admin but not owner, even though I push builds using my API key. So I don't have any notification emails other than those 4 for FLAW project.

**Comment by quyse** [comment]
Still happening for me every time.

Also there's an earlier report in butler's repo: https://github.com/itchio/butler/issues/107

**Comment by leafo** [comment]
should be fixed now, tell me if you still notice it

**Comment by quyse** [comment]
Sorry for late reply, I'm pushing very infrequently to my projects these days (more to the project belonging to other account for which I don't receive notification emails). So I pushed to my own project today and unfortunately got a double notification email like before:

![2017-09-21-093459_472x401_scrot](https://user-images.githubusercontent.com/416215/30681919-2fbd646c-9eb0-11e7-9aad-e6657005bbec.png)

**Comment by quyse** [comment]
Still happens every time. If it may help, here is the relevant piece of HTML in email. Seems like there's an excess iteration in some loop responsible of generating email's sections, but the second `<h2>` tag is empty - may it help you identify an issue with email generation?

```html
<h2>New builds are now live</h2>
<ul>
	<li>
		<a href="https://itch.io/game/edit/68784?open_channel=532539">Build 25</a>, <a href="https://itch.io/game/edit/68784?open_channel=213892">Build 86</a>, <a href="https://itch.io/game/edit/68784?open_channel=213893">Build 63</a> for <a href="REDACTED">FLAW</a>
	</li>
</ul>
<h2></h2>
<ul>
	<li>
		<a href="https://itch.io/game/edit/68784?open_channel=532539">Build 25</a>, <a href="https://itch.io/game/edit/68784?open_channel=213892">Build 86</a>, <a href="https://itch.io/game/edit/68784?open_channel=213893">Build 63</a> for <a href="REDACTED">FLAW</a>
	</li>
</ul>
```
