### ISSUE TITLE
Serve lato cyrillic variant for "ru" locale

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#953]
The version of Lato we serve only has Latin characters, so, if you don't have the complete Lato variant installed locally, here's what you see with the "ru" locale:

![image](https://user-images.githubusercontent.com/7998310/52137725-8f4b7300-264b-11e9-859a-3fee8e2daae0.png)

![image](https://user-images.githubusercontent.com/7998310/52137742-983c4480-264b-11e9-9ab0-02b6bf0799d6.png)

We can probably have a variant of the font that we serve only for the ru locale.

This will come in handy for when we have to ship https://www.google.com/get/noto/help/cjk/ ;)

**Comment by leafo** [comment]
I see there's an extended latin version of lato to download, is that the variant that has the needed characters?

**Comment by fasterthanlime** [comment]
From http://www.latofonts.com/lato-free-fonts/ :

> The ZIP con­tains two sub­fold­ers: Lato and Lato­Latin. The Lato sub­folder con­tains web­fonts with the com­plete char­ac­ter set (250−700 KB per font) while the Lato­Latin sub­folder con­tains smaller ver­sions that only include the most impor­tant glyphs for Euro­pean Latin-​​based lan­guages (75−200 KB per font). We do not pro­vide sup­port or instruc­tions how to install these fonts on your website!

I would assume "LatoLatin" is what we currently have and "Lato" is the full thing with Cyrillic, Greek, etc.

**Comment by quyse** [comment]
Seems like Lato font is fixed now, thanks! But, just so you are aware, fonts available for game pages don't work well. Serif, Sans-serif, Pixel fonts have the same problem, see:
![2019-02-06-010207_640x389_scrot](https://user-images.githubusercontent.com/416215/52307148-d79bc580-29aa-11e9-9706-c248d8a337ac.png)
Anonymous Pro, Lato, and custom Google fonts (supporting Cyrillic) seem to be fine.

**Comment by drxwat** [comment]
The issue still remains on the game jam page
![Screenshot 2023-12-14 at 12 31 40](https://github.com/itchio/itch.io/assets/6912873/503f6431-74e7-426e-9b40-c14be7c8abf3)

**Comment by quyse** [comment]
Indeed, it seems game jam pages miss the `--itchio_default_font` CSS variable.
