### ISSUE TITLE
On iOS Safari, can view optionally-paid PDFs but not free ones

### ISSUE THREAD

**Issue by omgitsraven** [itchio/itch.io#972]
First, a **working** example:
1) on iOS Safari, visit this page: https://florencesmithnicholls.itch.io/rayman-2-mini-zine (or any other itch page *with a PDF to download, which you **have the option** of paying for*)
2) Click 'download now'
3) Click 'no thanks'
4) Click 'download'
5) You are now viewing a PDF, everything is fine.

Now, a **broken** example:
1) on iOS Safari, visit this page: https://communistsister.itch.io/i-have-always-liked-sci-fi-anime-and-sex (or any other itch page with a PDF to download, which you **do NOT** have the possibility of paying for)
2) Click 'download'.
3) A screen pops up that says "thanks for downloading", but no download begins, and the browser does not navigate to viewing a PDF or anything. It just sits on this page and there's no way to see the content.

**Comment by leafo** [comment]
Do you know if your browser has a pop up blocker? If so, can you check if it's blocking the popup for the download on the free pdf?

**Comment by omgitsraven** [comment]
I'm not using any kind of pop-up blocker; I'm not sure if such a thing exists for iOS Safari.

**Comment by leafo** [comment]
sorry for takings some to respond. It should be fixed now

**Comment by omgitsraven** [comment]
It's not fixed; the problem is still happening.

(In fact it's gotten slightly worse; in the "working example" that I gave, I now have to click the download button twice in order to view the PDF. The broken example still doesn't work at all.)

**Comment by st33d** [comment]
Same problem here. I can't download a game that has no price option on iOS Safari:
https://qwo.itch.io/technoshockers

There is no popup blocker that I'm aware of.
